version: "3.8"
services:

  db:
    image: mysql:5.7.12
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zar
    volumes:
      - app-db-data:/var/lib/mysql/

  backend:
    stdin_open: true
    tty: true
    ports:
      - "80:80" 
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - ROLLBAR_ENABLED=${ROLLBAR_ENABLED}
      - ROLLBAR_ENV=${ROLLBAR_ENV}
      - ROLLBAR_KEY=${ROLLBAR_KEY}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - DEBUG=true
    logging:
      driver: json-file
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # This command comes with the base image:
    command: /start-reload.sh

  redis:
    image: "redis:alpine"
    command: redis-server --bind 0.0.0.0 --port 6379 --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru --save "" --appendonly no
    ports:
      - "6379"

volumes:
  app-db-data:

