version: "3.8"
services:

  db:
    image: mysql:5.7.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zar
    volumes:
      - app-db-data:/var/lib/mysql/

  backend:
    stdin_open: true
    tty: true
    ports:
      - "80:80" 
    volumes:
      - ./backend/app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN}
      - DEBUG=true
    logging:
      driver: json-file
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # This command comes with the base image:
    command: /start-reload.sh

volumes:
  app-db-data:

