version: "3.8"
services:
      
  backend:
    image: '${DOCKER_IMAGE_BACKEND}:${TAG-latest}'
    ports:
      - "80:80" 
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - DEBUG=${DEBUG-false}
      - ROLLBAR_ENABLED=${ROLLBAR_ENABLED}
      - ROLLBAR_ENV=${ROLLBAR_ENV}
      - ROLLBAR_KEY=${ROLLBAR_KEY}
    logging:
      driver: awslogs
      options:
        mode: non-blocking
        max-buffer-size: 4m
        awslogs-region: us-east-1
        awslogs-group: zar
        awslogs-create-group: "true"
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

