"""Initial model again

Revision ID: 0b840782b66f
Revises: 
Create Date: 2020-10-27 17:24:10.636183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b840782b66f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vid', sa.String(length=24), nullable=True),
    sa.Column('sid', sa.String(length=36), nullable=True),
    sa.Column('cid', sa.String(length=36), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_page_cid'), 'page', ['cid'], unique=False)
    op.create_index(op.f('ix_page_created_at'), 'page', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_sid'), 'page', ['sid'], unique=False)
    op.create_index(op.f('ix_page_uid'), 'page', ['uid'], unique=False)
    op.create_index(op.f('ix_page_vid'), 'page', ['vid'], unique=False)
    op.create_table('track',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=True),
    sa.Column('vid', sa.String(length=24), nullable=True),
    sa.Column('sid', sa.String(length=36), nullable=True),
    sa.Column('cid', sa.String(length=36), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referer', sa.String(length=2048), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_track_cid'), 'track', ['cid'], unique=False)
    op.create_index(op.f('ix_track_created_at'), 'track', ['created_at'], unique=False)
    op.create_index(op.f('ix_track_sid'), 'track', ['sid'], unique=False)
    op.create_index(op.f('ix_track_uid'), 'track', ['uid'], unique=False)
    op.create_index(op.f('ix_track_vid'), 'track', ['vid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_vid'), table_name='track')
    op.drop_index(op.f('ix_track_uid'), table_name='track')
    op.drop_index(op.f('ix_track_sid'), table_name='track')
    op.drop_index(op.f('ix_track_created_at'), table_name='track')
    op.drop_index(op.f('ix_track_cid'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_page_vid'), table_name='page')
    op.drop_index(op.f('ix_page_uid'), table_name='page')
    op.drop_index(op.f('ix_page_sid'), table_name='page')
    op.drop_index(op.f('ix_page_created_at'), table_name='page')
    op.drop_index(op.f('ix_page_cid'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
