"""vid col len, add sid to track_call

Revision ID: 13eac0b0e923
Revises: 83fcbeb5dcd4
Create Date: 2021-07-14 16:22:27.645299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13eac0b0e923'
down_revision = '83fcbeb5dcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'vid',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('track', 'vid',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.add_column('track_call', sa.Column('sid', sa.String(length=36), nullable=True))
    op.drop_index('ix_track_call_call_from', table_name='track_call')
    op.create_index(op.f('ix_track_call_sid'), 'track_call', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_call_sid'), table_name='track_call')
    op.create_index('ix_track_call_call_from', 'track_call', ['call_from'], unique=False)
    op.drop_column('track_call', 'sid')
    op.alter_column('track', 'vid',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=24),
               existing_nullable=True)
    op.alter_column('page', 'vid',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=24),
               existing_nullable=True)
    # ### end Alembic commands ###
