"""add number pool tables

Revision ID: 18bfff6fee6c
Revises: 267dcc70010a
Create Date: 2021-06-11 16:32:54.944286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18bfff6fee6c"
down_revision = "267dcc70010a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pools",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("properties", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_pool_created_at"), "pools", ["created_at"], unique=False)
    op.create_table(
        "pool_numbers",
        sa.Column("pool_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("pool_id", "number"),
        mysql_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_pool_numbers_created_at"), "pool_numbers", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pool_numbers_created_at"), table_name="pool_numbers")
    op.drop_table("pool_numbers")
    op.drop_index(op.f("ix_pool_created_at"), table_name="pools")
    op.drop_table("pools")
    # ### end Alembic commands ###
