"""add from_route_cache flag

Revision ID: 3ac9f4cfbd89
Revises: 13eac0b0e923
Create Date: 2021-07-20 13:23:00.280826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac9f4cfbd89'
down_revision = '13eac0b0e923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_call', sa.Column('from_route_cache', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_call', 'from_route_cache')
    # ### end Alembic commands ###
