"""Add host, remove url

Revision ID: b133fdee97b8
Revises: 0b840782b66f
Create Date: 2020-10-27 17:46:34.681055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b133fdee97b8'
down_revision = '0b840782b66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('host', sa.String(length=256), nullable=True))
    op.drop_column('page', 'url')
    op.add_column('track', sa.Column('host', sa.String(length=256), nullable=True))
    op.drop_column('track', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('url', mysql.VARCHAR(length=2048), nullable=True))
    op.drop_column('track', 'host')
    op.add_column('page', sa.Column('url', mysql.VARCHAR(length=2048), nullable=True))
    op.drop_column('page', 'host')
    # ### end Alembic commands ###
