"""call_enrichment

Revision ID: c177671d8cc2
Revises: 3ac9f4cfbd89
Create Date: 2026-07-30 17:46:12.015956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c177671d8cc2'
down_revision = '3ac9f4cfbd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_enrichment',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('call_from', sa.String(length=15), nullable=False),
    sa.Column('call_to', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('from_zip', sa.String(length=10), nullable=True),
    sa.Column('trusted_zip', sa.String(length=10), nullable=True),
    sa.Column('trust_reason', sa.String(length=64), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('call_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_call_enrichment_created_at'), 'call_enrichment', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_enrichment_created_at'), table_name='call_enrichment')
    op.drop_table('call_enrichment')
    # ### end Alembic commands ###
